image: "docker:latest"

stages:
  - naming
  - build_maxima_base
  - build_go
  - build_maxima_go

variables:
  GIT_SUBMODULE_STRATEGY: normal
  BASEIMAGE:  maxima_base
  REGISTRY: 1

naming:
  stage: naming
  tags:
    - docker
  except:
    - master
  script:
    - STACK_VERSION="$(echo $CI_COMMIT_REF_NAME | sed "s/stack\-//g")"
    - echo $STACK_VERSION
   
build_maxima_base:
  stage: build_maxima_base
  tags:
    - docker
  except:
    - master
  only:
    changes:
      - maxima_base/**
  script:
    - a="$(echo $CI_COMMIT_REF_NAME | sed "s/stack\-//g")"
    - cd maxima_baseimage
    - docker build -t $BASEIMAGE .

build_go:
  stage: build_go
  image: golang
  tags:
    - docker
  except:
    - master
  only:
    changes:
      - golang/**
  script:
    - cd golang/src/web
    - go build && GOBIN=golang/bin && go install
    - cp golang/bin/web maxima_go/bin/web

build_maxima_go:
  stage: build_maxima_go
  tags:
    - docker
  except:
    - master
  only:
    changes:
      - maxima_go/**
  script:
    - cd maxima_go
    - docker build -t maximago .
