stages:
  - build_webservice
  - build_image

steve_jobs:
  stage: build_webservice
  image: golang:1.15
  script:
    - ./buildweb.sh
  artifacts:
    paths:
    - bin/web
    expire_in: 1 week

build_webservice:
  stage: build_image
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DH_TOKEN" | docker login --username $DH_USER --password-stdin
  script:
    - ./build.sh "$DH_REGISTRY" "$CI_COMMIT_TAG"
