stages:
  - build_webservice
  - test_maxima

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REGISTRY: "172.30.190.249:5000"
  DB: "pgsql"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"

# gitlab ci script taken from https://gist.github.com/danielneis/5c6140ec8150c6151a54bccd26950278


cache:
  paths:
  - $HOME/.compose/cache

build_webservice:
  image: "docker:latest"
  stage: build_webservice
  needs:
    - project: martin.heide/goe_web
      job: steve_jobs
      ref: master
      artifacts: true
  tags:
    - docker
  script:
    - ./build.sh ${REGISTRY}

test_maxima:
  image: "$REGISTRY/moodle-ci-stack"
  stage: test_maxima
  services:
  - postgres:latest
  variables:
    MOODLE_BRANCH: "MOODLE_37_STABLE"
    QSTACK_VERSION: "v4.3.2"
  tags:
    - docker
  script:
    - bash testimage.sh
