services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
 
stages:
  - steve
  - build_webservice

steve_jobs:
  stage: steve
  image: golang
  tags:
    - docker
  script:
    - ./buildweb.sh
  artifacts:
    paths:
    - bin/web
    expire_in: 1 week

build_webservice:
  image: docker:dind
  stage: build_webservice
  tags:
    - docker
  before_script:
    - docker login -u $DH_USER -p $DH_TOKEN $DH_REGISTRY
  script:
    - ./build.sh "$DH_REGISTRY" "$CI_COMMIT_TAG"
