stages:
  - steve
  - build_webservice

steve_jobs:
  stage: steve
  image: golang
  tags:
    - docker
  script:
    - ./buildweb.sh
  artifacts:
    paths:
    - bin/web
    expire_in: 1 week

build_webservice:
  services:
    - name: docker:19.03.0-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  image: docker:19.03.0
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  stage: build_webservice
  tags:
    - docker
  before_script:
    - docker login -u $DH_USER -p $DH_TOKEN $DH_REGISTRY
  script:
    - ./build.sh "$DH_REGISTRY" "$CI_COMMIT_TAG"
