image: "docker:latest"

stages:
  - build_maxima_base
  - build_submodule
  - build_maxima_webservice

variables:
  GIT_SUBMODULE_STRATEGY: normal
  REGISTRY: ""
  BASE1: ${REGISTRY}maxima_base:0.1
  BASE2: ${REGISTRY}maxima_base:latest
  name: ${CI_COMMIT_REF_NAME}

build_maxima_base:
  stage: build_maxima_base
  tags:
    - docker
  except:
    - master
  only:
    changes:
      - maxima_base/**
  script:
    - cd maxima_baseimage
    - docker build -t ${BASE1} -t ${BASE2} .
#   - docker push ${BASE1} ${BASE2}

build_submodule
  stage: build_submodule
  image: golang
  tags:
    - docker
#  except:
#    - master
  only:
    changes:
      - go_web/**
      - webservice/**
  script:
    - cd goe_web/src/web
    - go build && GOBIN=${CI_PROJECT_DIR}/goe_web/bin go install

build_maxima_webservice:
  stage: build_maxima_webservice
  tags:
    - docker
  except:
    - master
  only:
    changes:
      - maxima_baseimage/**
      - go_web/**
      - maxima_webservice/**
  script:
    - a="$(echo $CI_COMMIT_REF_NAME | sed "s/stack\-//g")"
    - echo ${a}
    - echo ${name}
    - cp go_web/bin/web ${CI_PROJECT_DIR}/maxima_webservice/bin/web
    - cd maxima_webservice
    - docker build -t maximago --build-arg BASEIMAGE=${BASE2} .
