image: "docker:latest"

stages:
  - naming
  - build_maxima_base
  - build_go
  - build_maxima_go

variables:
  GIT_SUBMODULE_STRATEGY: normal
  BASEIMAGE: maxima:$STACK_VERSION

job_naming:
  stage: naming
  tags:
    - docker
  script:
   - STACK_VERSION="$(echo $CI_COMMIT_REF_NAME | sed "s/stack\-//g")"
   

job_build_maxima_base:
  stage: build_maxima_base
  tags:
    - docker
  only:
    changes:
      - maxima_baseimage/**
  script:
    - a="$(echo $CI_COMMIT_REF_NAME | sed "s/stack\-//g")"
    - cd maxima_baseimage
    - docker build -t $BASEIMAGE

job_build_go:
  stage: build_go
  image: golang:stable
  tags:
    - docker
  only:
    changes:
      - golang/**
  script:
    - cd golang/src/web
    - go build && GOBIN=/golang/bin && go install
    - cp /golang/bin/web /maxima_go/bin/web

job_build_maxima_go:
  stage: build_maxima_go
  tags:
    - docker
  only:
    changes:
      - maxima_baseimage/**
      - golang/**
      - maxima_go/**
