stages:
  - steve
  - build_webservice

# gitlab ci script taken from https://gist.github.com/danielneis/5c6140ec8150c6151a54bccd26950278

steve_jobs:
  stage: steve
  image: golang
  tags:
    - docker
  script:
    - ./buildweb.sh
  artifacts:
    paths:
    - bin/web
    expire_in: 1 week

build_webservice:
  image: "docker:latest"
  stage: build_webservice
  tags:
    - docker
  before_script:
    - docker login -u $DH_USER -p $DH_TOKEN $DH_REGISTRY
  script:
    - ./build.sh "$DH_REGISTRY" "$CI_COMMIT_TAG"
