image: "docker:latest"

stages:
  - build_submodule
  - build_webservice

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REGISTRY: "172.30.190.249:5000"

build_webservice:
  stage: build_webservice
  needs:
    - project: martin.heide/goe_web
      job: steve_jobs
      ref: master
      artifacts: true
  tags:
    - docker
  except:
    - master
  script:
    - ./build.sh ${REGISTRY}
