stages:
  - steve
  - build_webservice

steve_jobs:
  stage: steve
  image: golang
  script:
    - echo "Golang version is `go version`"
    - ./buildweb.sh
  artifacts:
    paths:
    - bin/web
    expire_in: 1 week

build_webservice:
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  stage: build_webservice
  before_script:
    - echo "$DH_TOKEN" | docker login --username $DH_USER --password-stdin
  script:
    - ./build.sh "$DH_REGISTRY" "$CI_COMMIT_TAG"
